# Site settings
title: Makeup Artist Landing Page
description: Order 

baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site


# Build settings
encoding: utf-8
markdown: kramdown
permalink: /:title.html

include: [.htaccess]

# Social contacts
facebook: https://www.facebook.com/pages/MAKE-MY-VISA/440928226067863
vk: https://vk.com/club94548539
email: info@make-my-visa.com.ua